[CmdletBinding()]
param(
    [string]$FontPath = "$env:WINDIR\Fonts\simhei.ttf",
    [string]$OutputPath = "",
    [string]$AssetPath = ""
)

$ErrorActionPreference = "Stop"
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    $OutputPath = Join-Path $projectRoot "Drivers\User\Src\lv_font_gb2312_16.c"
}
if ([string]::IsNullOrWhiteSpace($AssetPath)) {
    $AssetPath = Join-Path $projectRoot "assets\GB2312.FNT"
}
$assetHeaderPath = Join-Path $projectRoot "Drivers\User\Inc\ui_font_asset.h"

if (-not (Test-Path -LiteralPath $FontPath -PathType Leaf)) {
    throw "Chinese font file not found: $FontPath"
}

$npxCommand = Get-Command npx -ErrorAction Stop
$encoding = [System.Text.Encoding]::GetEncoding(
    936,
    [System.Text.EncoderExceptionFallback]::new(),
    [System.Text.DecoderExceptionFallback]::new()
)
$symbolsBuilder = [System.Text.StringBuilder]::new()

# GB2312 level 1/2 ideographs occupy CP936 B0A1..F7FE. Keeping the exact
# character list avoids embedding the entire 20k+ CJK Unified Ideographs range.
for ($lead = 0xB0; $lead -le 0xF7; $lead++) {
    for ($trail = 0xA1; $trail -le 0xFE; $trail++) {
        try {
            $character = $encoding.GetString([byte[]]@($lead, $trail))
            if ($character.Length -eq 1) {
                [void]$symbolsBuilder.Append($character)
            }
        }
        catch [System.Text.DecoderFallbackException] {
            # Ignore undefined CP936 slots.
        }
    }
}

$symbols = $symbolsBuilder.ToString()
if ($symbols.Length -lt 6700) {
    throw "Unexpected GB2312 symbol count: $($symbols.Length)"
}

& $npxCommand.Source --yes "lv_font_conv@1.5.3" `
    --size 16 `
    --bpp 2 `
    --format lvgl `
    --font $FontPath `
    --symbols $symbols `
    --no-compress `
    --no-prefilter `
    --no-kerning `
    --lv-include "lvgl.h" `
    --lv-font-name "lv_font_gb2312_16" `
    --lv-fallback "lv_font_simsun_16_cjk" `
    --output $OutputPath

if ($LASTEXITCODE -ne 0) {
    throw "lv_font_conv failed with exit code $LASTEXITCODE"
}

$fontSource = [System.IO.File]::ReadAllText($OutputPath)

# Extract the generated uncompressed bitmap into a standalone W25Q64 package.
# Only the much smaller glyph descriptors and Unicode maps remain in MCU Flash.
$bitmapPattern = '(?s)static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap\[\] = \{(.*?)\r?\n\};'
$bitmapMatch = [regex]::Match($fontSource, $bitmapPattern)
if (-not $bitmapMatch.Success) {
    throw "Generated glyph bitmap was not found"
}

$hexMatches = [regex]::Matches($bitmapMatch.Groups[1].Value, '0x([0-9a-fA-F]+)')
$bitmap = [byte[]]::new($hexMatches.Count)
for ($index = 0; $index -lt $hexMatches.Count; $index++) {
    $bitmap[$index] = [Convert]::ToByte($hexMatches[$index].Groups[1].Value, 16)
}
if ($bitmap.Length -eq 0 -or $bitmap.Length -gt 0x7FFE0) {
    throw "Unexpected bitmap size: $($bitmap.Length)"
}

$crc = [uint32]::MaxValue
foreach ($value in $bitmap) {
    $crc = [uint32]($crc -bxor $value)
    for ($bit = 0; $bit -lt 8; $bit++) {
        if (($crc -band 1) -ne 0) {
            $crc = [uint32](($crc -shr 1) -bxor 0xEDB88320)
        }
        else {
            $crc = [uint32]($crc -shr 1)
        }
    }
}
$crc = [uint32]($crc -bxor [uint32]::MaxValue)

$descriptorStart = $fontSource.IndexOf('static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {')
$descriptorEnd = $fontSource.IndexOf('};', $descriptorStart)
if ($descriptorStart -lt 0 -or $descriptorEnd -lt 0) {
    throw "Generated glyph descriptors were not found"
}
$descriptorBlock = $fontSource.Substring($descriptorStart, $descriptorEnd - $descriptorStart)
$glyphCount = [regex]::Matches($descriptorBlock, '\.bitmap_index').Count
if ($glyphCount -lt 6700) {
    throw "Unexpected generated glyph count: $glyphCount"
}

$assetDirectory = Split-Path -Parent $AssetPath
if (-not (Test-Path -LiteralPath $assetDirectory)) {
    [void](New-Item -ItemType Directory -Path $assetDirectory)
}

$assetStream = [System.IO.File]::Open($AssetPath,
    [System.IO.FileMode]::Create,
    [System.IO.FileAccess]::Write,
    [System.IO.FileShare]::None)
try {
    $writer = [System.IO.BinaryWriter]::new($assetStream)
    try {
        $writer.Write([uint32]0x32464247) # "GBF2"
        $writer.Write([uint16]1)
        $writer.Write([uint16]32)
        $writer.Write([uint32]$bitmap.Length)
        $writer.Write([uint32]$crc)
        $writer.Write([uint32]$glyphCount)
        $writer.Write([uint16]16)
        $writer.Write([byte]2)
        $writer.Write([byte]0)
        $writer.Write([uint64]0)
        $writer.Write($bitmap)
    }
    finally {
        $writer.Dispose()
    }
}
finally {
    $assetStream.Dispose()
}

$assetHeader = @"
#ifndef UI_FONT_ASSET_H
#define UI_FONT_ASSET_H

/* Generated by tools/generate_lvgl_gb2312_font.ps1. */
#define UI_FONT_ASSET_MAGIC          0x32464247U
#define UI_FONT_ASSET_VERSION        1U
#define UI_FONT_ASSET_BITMAP_SIZE    $($bitmap.Length)U
#define UI_FONT_ASSET_BITMAP_CRC32   0x$($crc.ToString('X8'))U
#define UI_FONT_ASSET_GLYPH_COUNT    $($glyphCount)U
#define UI_FONT_ASSET_PIXEL_SIZE     16U
#define UI_FONT_ASSET_BPP            2U

#endif /* UI_FONT_ASSET_H */
"@
[System.IO.File]::WriteAllText(
    $assetHeaderPath,
    $assetHeader,
    [System.Text.UTF8Encoding]::new($false)
)

# Keep the generated Unicode maps and metrics, but redirect bitmap access to
# the small QSPI-backed glyph cache. ASCII remains in the built-in fallback.
$fontSource = [regex]::Replace(
    $fontSource,
    '(?s)^/\*\*\*.*?\*/',
    "/*******************************************************************************`r`n * GB2312 16 px, 2 bpp. Bitmap payload: W25Q64 GB2312.FNT.`r`n ******************************************************************************/",
    1
)
$fontSource = [regex]::Replace(
    $fontSource,
    $bitmapPattern,
    "/* Glyph bitmaps are stored in the W25Q64 UI-font partition. */",
    1
)
$firstEndif = $fontSource.IndexOf('#endif')
if ($firstEndif -lt 0) {
    throw "Generated include block is malformed"
}
$insertAt = $firstEndif + '#endif'.Length
$fontSource = $fontSource.Insert($insertAt, "`r`n`r`n#include `"ui_font_storage.h`"")
$fontSource = $fontSource.Replace('.glyph_bitmap = glyph_bitmap,', '.glyph_bitmap = NULL,')
$fontSource = $fontSource.Replace('.get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,', '.get_glyph_dsc = UI_FontStorage_GetGlyphDsc,')
$fontSource = $fontSource.Replace('.get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,', '.get_glyph_bitmap = UI_FontStorage_GetBitmap,')

# LVGL 8.1.1 in this project already contains lv_font_t.fallback and follows it
# during glyph lookup. lv_font_conv only emits this initializer for LVGL 8.2+,
# which would disconnect the built-in ASCII font from this CJK-only asset.
$fallbackPattern = '(?m)^#if LV_VERSION_CHECK\(8, 2, 0\) \|\| LVGL_VERSION_MAJOR >= 9\r?\n\s*\.fallback = &lv_font_simsun_16_cjk,\r?\n#endif'
if (-not [regex]::IsMatch($fontSource, $fallbackPattern)) {
    throw 'Generated fallback block was not found'
}
$fontSource = [regex]::Replace(
    $fontSource,
    $fallbackPattern,
    '    .fallback = &lv_font_simsun_16_cjk,',
    1
)

# Match the existing SimSun fallback line box so mixed glyphs stay aligned.
$fontSource = [regex]::Replace($fontSource, '\.line_height = \d+,', '.line_height = 19,', 1)
[System.IO.File]::WriteAllText(
    $OutputPath,
    $fontSource,
    [System.Text.UTF8Encoding]::new($false)
)

Write-Host "Generated $($symbols.Length) GB2312 symbols"
Write-Host "Descriptors: $OutputPath"
Write-Host "W25Q64 asset: $AssetPath ($($bitmap.Length + 32) bytes, CRC32 0x$($crc.ToString('X8')))"
