#ifndef UI_FONT_ASSET_H
#define UI_FONT_ASSET_H

/* Generated by tools/generate_lvgl_gb2312_font.ps1. */
#define UI_FONT_ASSET_MAGIC          0x32464247U
#define UI_FONT_ASSET_VERSION        1U
#define UI_FONT_ASSET_BITMAP_SIZE    405258U
#define UI_FONT_ASSET_BITMAP_CRC32   0xF0E0D11AU
#define UI_FONT_ASSET_GLYPH_COUNT    6764U
#define UI_FONT_ASSET_PIXEL_SIZE     16U
#define UI_FONT_ASSET_BPP            2U

#endif /* UI_FONT_ASSET_H */